export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_BY_SEARCH = "GET_COUNTRIES_BY_SEARCH";
export const POST_ACTIVITIES = "POST_ACTIVITIES";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const ORDER_BY_ALPHABET = "ORDER_BY_ALPHABET";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
export const FILTER_COUNTRIES_BY_ACTIVITY = "FILTER_COUNTRIES_BY_ACTIVITY";
export const SET_DEFAULT_PAGE = "SET_DEFAULT_PAGE";
export const ERROR = "ERROR"

